version: 2.1
parameters:
  GHA_Event:
    type: string
    default: ""
  GHA_Actor:
    type: string
    default: ""
  GHA_Action:
    type: string
    default: ""
  GHA_Meta:
    type: string
    default: ""

jobs:
    build:
      docker:
        - image: circleci/python:3.7
      working_directory: /home/circleci/project
      steps:
                  # Obtain repo from the GitHub
        - checkout
                  # Create a virtual environment and install dependencies
        - run:
            name: install dependencies
            command: |
              ls -a
              pwd  
                  # sudo apt-get install python3-venv --fix-missing
                  #         pip install --upgrade virtualenv
                  # ls -l         
              python3 -m venv venv
              pwd 
              . venv/bin/activate
              /home/circleci/project/venv/bin/python3 -m pip install --upgrade pip
              pip install -r myreq.txt
                  # Run coding convention software plus tester
        - run:
            name: run tests
            command: |
              . venv/bin/activate
              flake8 --exclude=venv* --statistics
                                # pytest -v --cov=calculator
              pytest --junitxml=test-results/junit.xml
        - store_test_results:
            path: test-results
        - store_artifacts:
            path: test-results

workflows:
  push:
    jobs:  
      - build 